pymonetdb/mapi.py

The server might respond with comments (lines starting with the char
'#') after a command. This is very useful for debugging. Use the logger
to capture these messages exactly as is done in the login case.

Handle MSG_INFO as a command response

---

pymonetdb/mapi.py
test/requirements.txt
test/test_multiline.py
tox.ini

This PR includes a test suite that mocks connections to MonetDB in order to test parts of the pymonetdb module. The first test in it mocks `mapi.Connection._putblock` and `mapi.Connection._getblock`, in order to test multi line responses from the server. 
Also this PR adds support for the case of failed transactions in auto-commit mode.

Multiline handling

---

pymonetdb/mapi.py

In python3 encode was applied after after splicing the string. With encode, utf-8 characters are potentially expanded to multiple octets. For a given block that exceeded MAX_PACKAGE_LENGTH this resulted in the
last few octets falling off a package.

fix cutoff long packets with utf-8 characters

---

pymonetdb/sql/cursors.py
test/test_dbapi2.py

https://www.python.org/dev/peps/pep-3114/
Without this change
```python
for row in cursor:
etc
```
would give an error
```
TypeError: iter() returned non-iterator of type 'Cursor'
```

In python3 next has been renamed to __next__

---

pymonetdb/sql/connections.py
test/test_dbapi2.py

If the user ends a query with a comment, the query is not executed.
This PR adds a test and the fix.

Queries ending with comments fail to execute

---

pymonetdb/control.py
pymonetdb/mapi.py
pymonetdb/sql/connections.py

This PR allows to configure the socket timeout when connecting the monetdb server,
for both `sql.Connection` and `Control`.
Currently, a timeout can be set only once the connection is already established.

add timeout for server connection

---

pymonetdb/mapi.py

The error messages will be more aligned (and sql conforming, using sqlstate numbers). This creates more compilated error messages of the form
exceptionName:function:SQLSTATE NNNNN ! message
niels

upcoming monetdb version will have more complicate error messages

---

pymonetdb/mapi.py

In stream.c, TCP keepalive is enabled. But it is not in client side. When client is running in docker swarm, long idle is broken by docker swarm and pymonetdb client can not detect broken connection.

Enable TCP_KEEPALIVE to keep consistent with stream.c

---

pymonetdb/sql/pythonize.py
tests/test_oid.py
tests/test_unicode.py

For now we will just return the string representation, just like mclient does.

Fix support for OID type

---

pymonetdb/sql/monetize.py
pymonetdb/sql/pythonize.py
tests/test_capabilities.py
tests/test_dbapi2.py
tests/test_pythonize.py
tests/test_unicode.py

This PR implements storing and retrieving Python 3 bytes objects as MonetDB blobs:
```python
import pymonetdb
c = pymonetdb.connect("demo", user="monetdb", password="monetdb", host="monet")
c.set_autocommit(True)
cc = c.cursor()
x = b'binary data'
cc.execute("drop table if exists tbl")
cc.execute("create table tbl(b blob)")
cc.execute("insert into tbl values (%s)", [x])
cc.execute("select * from tbl")
y = cc.fetchall()[0][0]
assert(x == y)
```

Fix blob handling

---

pymonetdb/mapi.py
pymonetdb/sql/connections.py

On the default branch you can pass options like auto commit, reply size and time zone directly in the authentication response, without having to round-trip several separate commands to set them. This improves startup time.
The change is backward compatible, the mechanism is only used if the server announces support for it.

Use new MAPI handshake options, if available

---

pymonetdb/mapi.py
pymonetdb/sql/connections.py
tests/test_mapi_uri.py
tox.ini

Allow to connect using a full mapi uri in place of the database parameter.
TCP syntax: `mapi:monetdb://[<username>[:<password>]@]<host>[:<port>]/<database>`
Unix domain syntax: `mapi:monetdb:///[<username>[:<password>]@]path/to/socket?database=<database>`

Allow to connect using a full mapi uri in place of the database parameter.

---

pymonetdb/sql/connections.py
pymonetdb/sql/monetize.py
pymonetdb/sql/pythonize.py
tests/test_capabilities.py
tests/test_monetize.py
tests/test_pythonize.py

If a datetime has a timezone, use TIMESTAMPTZ 'bla' instead of TIMESTAMP 'bla'. Conversely, when creating a datetime from an incoming value that has a time zone indicator, do not add it to the datetime but store it in its .tzinfo field.
This ensures that both naive and aware datetimes can safely roundtrip to and from the server, and that `SELECT now()` yields the expected value.
To make this work we have to set the session timezone at connect time. Most other language bindings already did this.

Improve timezone handling

---

pymonetdb/sql/debug.py
tests/test_udf.py

Fix issue #49. The problem was that as of Python3, pickle no longer returns strings but bytes objects. First I attempted to let the `export_parameters` function return a BLOB but that didn't work so in the mean time it returns a hex encoding of the bytes.
With this issue fixed I could test my fix for the deprecation warning that shows up in the tox output:
```
=============================== warnings summary ===============================
.tox/py310/lib/python3.10/site-packages/past/builtins/misc.py:45
/home/jvr/src/pymonetdb/.tox/py310/lib/python3.10/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
from imp import reload
```

Fix udf debugging and remove an annoying tox warning

---

pymonetdb/sql/pythonize.py
tests/test_temporal.py

strptime expected leading zeroes but MonetDB sends them without. Fixes #107.

Deal with dates before the year 1000

---

pymonetdb/sql/cursors.py

If a result set is larger than N rows, where N means 100 rows or whatever was set using `Connection.set_replysize`, only the first N rows are set to the client initially. The other rows remain on the server until the client asks for them. The client must send an explicit `Xclose` message to discard the server side row buffer when no more rows are needed.
In pymonetdb this happens when the cursor is closed or right before it executes another SQL statement.
The logic to do so was flawed:
```python
self._must_close_resultset = self.rowcount > len(self._rows)
```
Unfortunately, the rowcount is also used to hold the number of affected rows of for example INSERT statements. In such as case, `self.rowcount` would be greater than 0 and `self._rows` would be empty, leading to an unnecessary …

Suppress unnecessary Xclose messages

---

.github/workflows/pytest.yml
pymonetdb/mapi.py
tests/test_control.py

My ON CLIENT changes broke control connections to monetdb's unix domain socket (/tmp/.s.merovingian.50000). This PR fixes that. It also makes it much faster.
Fixes #111

Support local control connections again

---

pymonetdb/filetransfer/__init__.py
pymonetdb/mapi.py
tests/test_filetransfer.py

when trying to COPY INTO ON CLIENT for a file with a whitespace in its filename (eg `my file.csv` i realized that the client was hanging. since i was not sure whose fault that was i investigated both the server and the client and realized that they were in a state that seems as a deadlock.
for the server i had my connection's thread stuck at 
```c
// common/stream/socket_stream.c:127
ret = poll(&pfd, 1, (int) s->timeout);
```
and the client at
```py
n = self.socket.recv_into(view)
```
only after killing the client the server was logging
```txt
ON CLIENT: Invalid file transfer command: 'r 0 my file.csv'
```
apparently it was the client generating and sending the message to the server due to the erroneous split. 
now since looking at the code i'm not sure if that double `split()` of the …

Bug: filenames with whitespaces

---

pymonetdb/sql/cursors.py

We used `Cursor.nextset()` to fetch the next few rows from the current result set but [PEP-249](https://peps.python.org/pep-0249/#nextset) defines `.nextset()` to have a different meaning: it moves to the START OF THE NEXT RESULT SET.
There is no need to implement a replacement .nextset() method as PEP-249 explicitly states:
> If the database does not support the functionality required by the
> method, the interface should throw an exception in case the method
> is used.
>
> The preferred approach is to not implement the method and thus have
> Python generate an AttributeError in case the method is requested.
Note that neither the Postgres-, the MySQL- nor the Sqlite bindings implement `.nextset()` so I don't think we need to be in a great hurry to implement it.

Rename Cursor.nextset() to Cursor._nextchunk()

---

pymonetdb/sql/connections.py
pymonetdb/sql/cursors.py
tests/test_contextmanager.py

That is, the statement
with pymonetdb.connect('db') as conn, conn.cursor() as cursor:
cursor.execute("SELECT 42")
automatically closes the cursor and the connection regardless of whether .execute succeeds.
This is not required by DBAPI 2.0 but many other implementations do this as well.

Allow to use Connection and Cursor as context managers

---

pymonetdb/mapi.py

This forces an error message when accidentally connecting to a TLS server.
Also, surprisingly it seems to make connection setup slightly faster!

Send a number of NUL bytes on new TCP connections     
